### ISSUE TITLE
Add support for sqlalchemy 0.1.4

### ISSUE THREAD

**Issue by c-thiel** [ibmdb/python-ibmdbsa#98] opened 2021-03-16 08:40 UTC
In sqlalchemy 0.1.4 the sqlalchemy.connectors.zxJDBC class was removed on which ibm_db_sa depends.
The corresponding change is documented in the [changelog](https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html#change-8334d0f6902cd6997ca5d71ec25ec4b6).

As a quick fix it would already help to modify the `setup.py` to prevent installations from breaking.

**Comment by amukherjee28** [comment] 2021-03-16 10:10
Hi @c-thiel 

Thank you for the update.

We have a Min support and Max support version range.
Will maintain an update once installation starts breaking because of changes in sqlalchemy layer.

For now my suggestion would be to install sqlalchemy version 0.1.3 till we make a new release claiming support for the new sqlalchemy version support.

Thanks.

**Comment by EdCrux** [comment] 2021-03-18 20:38
You could use version 1.3.23

**Comment by FjedorGaede** [comment] 2021-03-30 10:00
Hi guys,

I also ran into this problem this moring setting up a new Python environment. Would appreciate a fix for this.

Have a  nice day

**Comment by uhinze** [comment] 2021-04-06 08:54
Until support for the recent alchemy version is there, it would be nice to at least state the incompatibility in the docs. For now, it says

> SQLAlchemy 0.7.3 or above.

and that's not true at the moment.

**Comment by amukherjee28** [comment] 2021-04-06 09:16
Hi,

The README is updated for the supported versions of sqlalchemy.
Testing is currently is progress with the latest version of sqlalchemy and once completed will be released.

Thanks.

**Comment by rolweber** [comment] 2021-06-01 14:45
I'm also running into this. Will downgrade sqlalchemy to 1.3 while waiting for the new release :-)

**Comment by arnabmukherjee-zebra** [comment] 2021-07-15 12:43
can you update the pypi [page](https://pypi.org/project/ibm-db-sa/) as well ?

**Comment by amukherjee28** [comment] 2021-07-19 09:32
New version is released and this issue had been addressed in the new release 0.3.7.

Please check and let me know if this can be closed.

**Comment by ilne** [comment] 2021-07-19 09:38
Confirmed working with ibm-db-sa-0.3.7 and SQLAlchemy-1.4.21. Thanks!

**Closed** 2021-07-19 09:58 UTC
